os:
  - osx
  - linux

language: swift
osx_image: xcode11
sudo: required

install: . CI/install.sh

script:
  - swiftlint
  - swift build
  - swift test

deploy:
  provider: script
  script: CI/release-version.sh
  on:
    branch: master
