image: swift:4.2.3

static-test: &static-test
    step:
        name: Static Tests
        script:
            - chmod +x ./CI/install-swiftlint.sh
            - ./CI/install-swiftlint.sh
            - swiftlint
test: &test
    step:
        name: Test
        script:
            - swift package resolve
            - swift package clean
            - swift test

pipelines:
    default:
#    - <<: *static-test
    - <<: *test
    branches:
        master:
 #           - <<: *static-test
            - <<: *test
            - step:
                name: Release
                script:
                    - chmod +x ./CI/release-version.sh
                    - ./CI/release-version.sh
