name: Swift Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  check-doc-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Calculate Documentation Coverage
        uses: MatsMoll/swift-doc@master
        with:
          inputs: "Sources"
          output: "dcov.json"
      - name: Check Documentation Percent
        run: sudo bash CI/check-percentage.sh dcov.json 0
          
  bionic-tests:
    needs: check-doc-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.3.0"
      - name: Run unit tests
        run: swift test --enable-test-discovery
        env:
          BUILD_TYPE: DEV
